# Generated by Django 3.0.2 on 2021-06-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0003_infomodel_consignee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infomodel',
            name='bool_eta',
            field=models.BooleanField(default=False, verbose_name='到着済'),
        ),
    ]
