# Generated by Django 3.0.2 on 2021-06-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0004_auto_20210623_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infomodel',
            name='cntr_eta',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='infomodel',
            name='final_update',
            field=models.DateField(auto_now=True),
        ),
    ]
