# Generated by Django 3.0.2 on 2021-06-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0005_auto_20210623_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infomodel',
            name='option',
            field=models.TextField(null=True),
        ),
    ]
